version: "3"

volumes:
  mongodb_volume:

services:
  tg_bot:
    build: tg_bot/
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - TOKEN= # токен telegram бота
      - HOST_URL= # URL сервера (если оставить HOST_URL пустымм, то бот запустится локально)
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных

  parser:
    build: parser/
    restart: always
    environment:
      - URL_INSTITUTES=https://www.istu.edu/schedule/ # URL на страницу с выбором института
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных
      - PARSE_TIME_HOURS=1 # задержка между циклами парсинга (в часах)


  notification_service:
    build: notification_service/
    restart: always
    environment:
      - TOKEN= # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных


  web_manager:
    build: web_manager/
    restart: always
    ports:
      - 0.0.0.0:8081:8081
    environment:
      - TOKEN= # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных


  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always